### PR TITLE
Implicit declarations

### PR DESCRIPTION
**Pull request by mig-hub**
Hello,

In my branch "implicit-declarations" I have made 2 commits which fix all the current implicit declaration warnings.
They were for hmac_sha1 in IoSHA1.c et for IoState_registerProtoWithFunc_ in a few addons.

I hope everything is ok.
Thank you,
mig

### CODE REVIEW

**Comment by stevedekorte** [comment]
Thanks for the request - github says I can't auto merge this, Could you fix and I'll pull?

**Comment by codymoorhouse** [comment]
I have sent Mig hub a pull request merging his branch with the master branch. Hopefully this will resolve his merge conflicts and his pull request will be able to be merged in after that.

**Comment by stevedekorte** [comment]
Thanks cody. Mig, I'm happy to pull your changes when ready.

**Comment by ales-tsurko** [comment]
#448

**Pull request closed without merging**
